config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'chess', to: 'static_pages#chess'
  get 'project_tracker', to: 'static_pages#project_tracker'
  get 'video_app', to: 'static_pages#video_app'
  get 'blog', to: 'static_pages#blog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/visit.rb
class Visit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @images = [
      'ruby.png',
      'rails.png',
      'javascript.png',
      'git.png',
      'html.png',
      'css.png',
      'react.png'
    ]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/blog.html.erb
<br/><br/>

<div class="container">
  <div class="box col-9">

    <h4 class="text-center">
      Blog site that allows for rich text editing of blog posts.
      <br/><br/>
      Built with HTML, CSS, PostgreSQL, Ruby on Rails
    </h4>

    <br/>

    <h3 class="container">
      <%= link_to 'Click to go to site', 'https://blog-andy-strube.herokuapp.com/' %>
    </h3>

    <br/>

    <h3 class="container">
      <%= link_to "Click to see github repo", "https://github.com/Learningstuff98/andy-strube-blog" %>
    </h3>

    <br/>

    <h3 class="container">
      <%= link_to 'Back To Home', root_path %>
    </h3>

  </div>
</div>

<br/>

<%= image_tag 'blogappgif.gif', class: 'container' %>

<br/><br/>

app/views/static_pages/chess.html.erb
<br/><br/>

<div class="container">
  <div class="box col-9">

    <h4 class="text-center">
      Chess app that lets users play against each other in real time.
      <br/><br/>
      Built with Ruby on Rails, React, Rspec, Websockets, PostgreSQL, CSS, HTML
    </h4>

    <br/>

    <h3 class="container">
      See info page on the live site for more information. Doesn't require logging in.
    </h3>

    <h3 class="container">
      <%= link_to 'Click to go to site', 'https://chess-andy-strube.herokuapp.com/' %>
    </h3>

    <br/>

    <h3 class="container">
      <%= link_to "Click to see github repo", "https://github.com/Learningstuff98/chess" %>
    </h3>

    <br/>

    <h3 class="container">
      <%= link_to 'Back To Home', root_path %>
    </h3>

  </div>
</div>

<br/>

<%= image_tag 'chessgif.gif', class: 'container' %>

<br/><br/>

app/views/static_pages/index.html.erb
<body>
  <div class="text-center">
    <%= image_tag 'me.JPG', class: 'portfolio-picture img-fluid' %>

    <br/><br/>

    <div class="container">
      <div class="box col-9">

        <h2>Andy Strube</h2>
        <h4>andystrube64@gmail.com</h4>
        <h4>
          <a class="link" href="https://github.com/Learningstuff98">Github</a>
          <a class="link" href="https://www.linkedin.com/in/andy-strube-6231ba152/">Linkedin</a>
          <a class="link" href="https://docs.google.com/document/d/1qm4nBdIZfsx8zh4IwYvkVuQYclpOXUCVxnC9vV3_eBM/edit">Resume</a>
        </h4>

        <br/>

        <h3>About me</h3>

        <h4>
          Welcome to my portfolio site!
          I origionally graduated from a bootcamp that taught Ruby on Rails.
          Since I graduated I've continued learning and imporving my programming
          skills. Below you'll find evidence that shows that I'm passionate and
          proactive about software developmet such as the open source contributions
          that I made to both the Ruby for Good Casa and Human Essentials applications
          along with my portfolio projects. I'm proudest of the chess app, so I definatly
          encourage giving that one a visit.
          <br/></br/>
          I'm excited to learn and solve problems so feel free to reach out to me! My
          cell number is (360) 901 - 1553 and my email is andystrube64@gmail.com.
        </h4>

        <br/>

        <h3>Volunteer Work with Ruby for Good</h3>

        <br/>

        <h3>Human Essentials</h3>

        <h4>
          Implemented full stack functionality that empowers non-technical site admins to edit user facing content dynamically across different domains
          along with a search feature that empowers users by allowing them to find information efficiently.
          Built with Ruby on Rails, Rspec, HTML, Bootstrap and Tailwindcss.
        </h4>

        <h4>
          <%= link_to 'See code examples', 'https://github.com/rubyforgood/human-essentials/commits?author=Learningstuff98' %>
        </h4>
 
        <br/>

        <h3>Casa</h3>

        <h4>
          Implemented full stack functionality that empowers non-technical admin users to create, edit and delete content, along with other site maintenance
          contributions such as writing tests and refactoring. Skills involved are Ruby on Rails, Rspec, HTML and CSS.          
        </h4>

        <h4>
          <%= link_to 'See code examples', 'https://github.com/rubyforgood/casa/commits?author=Learningstuff98' %>
        </h4>

        <br/>

        <h3>Education</h3>

        <h4>
          UC Berkeley Full Stack  Web Development Certification  March 2019 - August 2019
        </h4>

        <h4>
          6 month coding bootcamp that focused on learning how to make full stack websites using
          Ruby on Rails, Javascript and PostgreSQL.
        </h4>

        <br/>

        <h3>Technologies</h3>

        <br/>

        <% @images.each do |image| %>
          <%= image_tag image, class: 'tech-icon' %>
        <% end %>

        <br/><br/>

        <h2>Projects</h2>

        <br/>

        <hr class="divider-line">
        <h2>Chess</h2>
        <h4>
          Chess app that lets users play against each other in real time.
          <br/><br/>
          <%= link_to 'See Details', chess_path %>
        </h4>

        <br/>


        <hr class="divider-line">
        <h2>Project Tracker</h2>
        <h4>
          Users can start projects, make development stages along with issues and move issues across different stages.
          Other users can see the updates happening in real time.
          <br/><br/>
          <%= link_to 'See Details', project_tracker_path %>
        </h4>

        <br/>

        <hr class="divider-line">
        <h2>Blog App</h2>
        <h4>
          Blog site that allows for rich text editing of blog posts.
          <br/><br/>
          <%= link_to 'See Details', blog_path %>
        </h4>

      </div>
    </div>

    <br/><br/>

  </div>
</body>

app/views/static_pages/project_tracker.html.erb
<br/><br/>

<div class="container">
  <div class="box col-9">

    <h4 class="text-center">
      Users can start projects, make development stages along with issues and move issues across different stages.
      Other users can see the updates happening in real time.
      <br/><br/>
      Built with CSS, HTML, Ruby on Rails, React, Rspec, Websockets, PostgreSQL
    </h4>

    <br/>

    <h3 class="container">
      <%= link_to 'Click to go to site', 'https://project-tracker-andy-strube.herokuapp.com/' %>
    </h3>

    <br/>

    <h3 class="container">
      <%= link_to "Click to see github repo", "https://github.com/Learningstuff98/project-tracker" %>
    </h3>

    <br/>

    <h3 class="container">
      <%= link_to 'Back To Home', root_path %>
    </h3>

  </div>
</div>

<br/>

<%= image_tag 'project-tracker.gif', class: 'container' %>

<br/><br/>

app/views/static_pages/video_app.html.erb
<br/><br/>

<div class="container">
  <div class="box col-9">

    <h4 class="text-center">
      Users can start channels and upload videos to their channels. Users can make comments on videos. Users can subscribe to channels.
      <br/><br/>
      Built with HTML, CSS, PostgreSQL, Ruby on Rails, React, AWS, Rspec
    </h4>

    <br/>

    <h3 class="container">
      <%= link_to 'Click to go to site', 'https://video-app-andy-strube.herokuapp.com/' %>
    </h3>

    <br/>

    <h3 class="container">
      <%= link_to "Click to see github repo", "https://github.com/Learningstuff98/video_app" %>
    </h3>

    <br/>

    <h3 class="container">
      <%= link_to 'Back To Home', root_path %>
    </h3>

  </div>
</div>

<br/>

<%= image_tag 'videoappgif.gif', class: 'container' %>

<br/><br/>